export const guides={
 meta:{title:'Meta',status:'Guía de planeación · validar configuración en cuenta',steps:['Define el objetivo de campaña y la geografía donde existe distribución del producto. Separa las piezas de limpieza de las de Control Poros.','Compara una audiencia amplia con una hipótesis de interés contextual. Busca en el selector los términos disponibles; los ejemplos de esta guía no son IDs ni intereses garantizados.','Revisa en tu cuenta qué opciones funcionan como controles y cuáles como sugerencias. No interpretes una sugerencia como un límite de entrega.','Si tienes datos propios y permisos para utilizarlos, prepara una prueba de retargeting separada. Evalúa alcance, frecuencia y respuesta creativa antes de escalar.'],note:'La documentación pública de Meta solicitó acceso durante la revisión. Esta es una propuesta de trabajo: confirma la interfaz y las opciones habilitadas en Ads Manager.',sources:[['Meta · Información de Advantage+ audience','https://www.facebook.com/business/ads/meta-advantage-plus/audience']]},
 youtube:{title:'YouTube',status:'Documentación oficial revisada · 06 oct 2026',steps:['Define geografía y objetivo en una campaña de video compatible.','Crea un segmento personalizado con términos que describan intereses o intención; puedes agregar URLs y aplicaciones pertinentes.','En campañas que se muestran en propiedades de Google, revisa la opción basada en términos buscados. Fuera de ellas, esos términos se interpretan como intereses o intención.','Aplica el segmento donde lo permita el tipo de campaña y verifica el alcance estimado. Las URLs son señales de afinidad; no garantizan que el anuncio se publique en esos sitios.'],note:'Los ejemplos son hipótesis para probar. Un segmento de Google no equivale a un conjunto de palabras clave de Search.',sources:[['Google Ads · Segmentos personalizados','https://support.google.com/google-ads/answer/9805516']]},
 tiktok:{title:'TikTok',status:'Documentación oficial revisada · 06 oct 2026',steps:['En el grupo de anuncios, define ubicación y las variables demográficas que correspondan al plan.','Explora las opciones de intereses y comportamientos que estén disponibles. Busca temas relacionados con rutina y cuidado personal.','Construye pruebas con creadores y mensajes por momento de uso. Revisa si las opciones inteligentes amplían la selección inicial.','Contrasta los resultados con una audiencia amplia y revisa frecuencia y consumo de video. No traduzcas un hashtag directamente en un tamaño de audiencia.'],note:'Las categorías y posibilidades dependen de la cuenta y del mercado. Los ejemplos no son una lista confirmada de segmentos disponibles.',sources:[['TikTok Ads · Dimensiones de segmentación','https://ads.tiktok.com/resources/help/article/ad-targeting'],['TikTok Ads · Intereses','https://ads.tiktok.com/resources/help/article/interest-targeting']]},
 pinterest:{title:'Pinterest',status:'Documentación oficial revisada · 06 oct 2026',steps:['Confirma disponibilidad de compra para tu cuenta y mercado; abre la segmentación del grupo de anuncios.','Relaciona intereses y palabras clave con rutinas e ideas de cuidado que las personas guardarían.','Si hay una base propia disponible, evalúa audiencias de visitantes o interacción. Ajusta ubicación y otras variables pertinentes.','Revisa si Performance+ expande la selección y mide guardados, clics salientes y resultados del objetivo de campaña.'],note:'Las búsquedas sugeridas son ideas editoriales; no implican volumen medido ni disponibilidad comercial confirmada para esta cuenta.',sources:[['Pinterest · Opciones de segmentación','https://help.pinterest.com/en/business/article/targeting-overview']]},
 ctv:{title:'Connected TV',status:'Propuesta de compra · proveedor por definir',steps:['Selecciona el proveedor, inventario y cobertura efectiva en Colombia.','Solicita al proveedor las categorías contextuales y de audiencia disponibles, con su definición y origen.','Distingue alcance de hogares, dispositivos y personas. Alinea esta unidad antes de compararla con el universo de 7 millones de personas.','Acuerda frecuencia, reporte y método de deduplicación. No sumes directamente alcance de CTV con el de redes sociales.'],note:'No hay proveedor ni catálogo de segmentos confirmado. Esta ficha prepara el brief de compra; no representa una configuración disponible en una plataforma específica.',sources:[]}
};
export const audienceSignals={
 productivas:['rutina facial práctica','cuidado personal después del trabajo','organizar mi rutina'],
 madres:['tiempo para mí','rutina de autocuidado','cuidado facial sencillo'],
 deportistas:['rutina facial y vida activa','cuidado personal después de entrenar','bienestar cotidiano'],
 viajeras:['neceser de viaje','rutina facial de viaje','organizar productos de cuidado'],
 estudiantes:['cómo empezar una rutina facial','skincare accesible','rutina facial sencilla']
};
export const productSignals={limpieza:['pads de algodón','desmaquillado','limpieza facial'], 'control-poros':['qué son los pads de tratamiento','cuidado de poros','rutina con pads faciales']};
