// Editorial planning hypotheses. These are not platform segment IDs or measured audiences.
const profiles={
 productivas:{moment:'Al cerrar la jornada, entre llegar a casa y descansar.',contexts:['Rutinas de noche','Organización del tiempo','Maquillaje para la oficina','Autocuidado cotidiano'],clean:['cómo desmaquillarse al llegar del trabajo','algodón para retirar maquillaje','rutina de limpieza facial de noche','pads de algodón suaves'],pore:['diferencia entre limpiar y tratar la piel','pads faciales de tratamiento','orden de una rutina facial de noche','para qué sirven los pads control poros'],creative:'De la jornada al momento para ti: una rutina mostrada paso a paso.'},
 madres:{moment:'Una pausa personal dentro de la rutina de casa; hablarle como persona, no solo como mamá.',contexts:['Autocuidado en casa','Rutinas prácticas','Organización cotidiana','Belleza y bienestar'],clean:['rutina sencilla para desmaquillarse','pads para limpieza facial','algodón para agua micelar','limpieza facial en casa'],pore:['cómo incorporar pads a mi rutina','limpieza y tratamiento facial diferencias','qué son los pads control poros','rutina facial paso a paso'],creative:'Un momento que también es tuyo: mostrar el cuidado sin exigir una rutina perfecta.'},
 deportistas:{moment:'Después de entrenar, al regresar a casa y retomar la rutina de cuidado.',contexts:['Vida activa','Contenido de entrenamiento','Organización del bolso deportivo','Bienestar cotidiano'],clean:['qué llevar en el neceser del gimnasio','limpieza facial después de entrenar','pads de algodón para limpieza','rutina de cuidado y deporte'],pore:['orden de productos en la rutina facial','pads de tratamiento cómo funcionan','limpieza versus cuidado de poros','rutina facial para una vida activa'],creative:'Del bolso deportivo al tocador: distinguir el paso de limpieza del de tratamiento.'},
 viajeras:{moment:'Al preparar el neceser y mantener una rutina fuera de casa.',contexts:['Organización de equipaje','Neceseres de viaje','Escapadas de fin de semana','Rutinas fuera de casa'],clean:['qué llevar en el neceser de viaje','pads de algodón para desmaquillar','rutina de limpieza durante un viaje','organizar productos de cuidado personal'],pore:['cómo organizar mi rutina facial de viaje','pads de tratamiento facial','qué paso sigue después de la limpieza','diferencia entre pads de algodón y tratamiento'],creative:'Prepara tu neceser: identificar qué limpia y qué trata, conservando los empaques originales.'},
 estudiantes:{moment:'Entre clases y actividades, mientras aprende a construir su rutina. Propuesta dirigida a mayores de 18 años.',contexts:['Rutinas para principiantes','Vida universitaria','Tutoriales de maquillaje','Compras de cuidado personal'],clean:['cómo desmaquillarse correctamente','agua micelar con pads de algodón','rutina de limpieza para principiantes','pads redondos o cuadrados'],pore:['qué son los pads de tratamiento','en qué orden usar productos faciales','diferencia entre AHA y BHA en cosmética','pads control poros para qué sirven'],creative:'Limpieza o tratamiento: un tutorial que resuelve una duda a la vez.'}
};
export function signalPlan(audience,product,medium='meta'){
 const a=profiles[audience];if(!a||!['limpieza','control-poros'].includes(product))throw new Error('Contexto de señales inválido');
 const cleaning=product==='limpieza', searches=cleaning?a.clean:a.pore;
 const topics=cleaning?['Desmaquillado','Algodón cosmético','Agua micelar','Limpieza facial']:['Pads de tratamiento','Cuidado cosmético de poros','Textura y doble cara del pad','Educación sobre ingredientes'];
 const methods={
 meta:{place:'Conjunto de anuncios · opciones de audiencia disponibles en tu cuenta',input:'Busca familias de interés como belleza, cosmética y cuidado personal. Conserva solo las que aparezcan en el selector. Las búsquedas de abajo son ideas de mensajes: no se pegan como keywords de Meta.',test:'Compara audiencia amplia versus intereses disponibles, con la misma pieza, objetivo, ubicación y presupuesto. Registra si Advantage+ puede ampliar las sugerencias.',metric:'Costo por visita a la página de destino; alcance y frecuencia como control.'},
 youtube:{place:'Gestor de audiencias → Segmentos personalizados → nuevo segmento',input:'Prueba los términos sugeridos como señales de interés o intención. En campañas compatibles en propiedades de Google, evalúa la opción de personas que buscaron esos términos. No son keywords de una campaña Search.',test:'Compara un segmento de intención de producto con otro de contexto de rutina. Mantén el mismo video y objetivo; cambia una variable por prueba.',metric:'Tasa de visualización y costo por visualización; visitas a la página para campañas de consideración.'},
 tiktok:{place:'Grupo de anuncios · Intereses y comportamientos',input:'Busca categorías de belleza y cuidado personal disponibles. Usa los contextos para explorar contenido y creadores; los hashtags o frases no equivalen automáticamente a segmentos seleccionables.',test:'Compara audiencia amplia con categorías de interés disponibles. Usa el mismo video vertical y registra si la expansión inteligente está activa.',metric:'Retención del video, costo por visita a la página y frecuencia.'},
 pinterest:{place:'Grupo de anuncios → Segmentación → intereses / palabras clave',input:'Organiza las búsquedas sugeridas en un grupo temático y valida las opciones de keywords de la cuenta. Prueba intereses en otro grupo; revisa la expansión Performance+ y disponibilidad comercial.',test:'Compara palabras clave de intención con intereses de rutina. Usa el mismo Pin, destino y presupuesto para interpretar la diferencia.',metric:'Clics salientes y su costo; guardados como señal de consideración.'},
 ctv:{place:'Brief al proveedor de Connected TV · inventario y cobertura por confirmar',input:'Solicita paquetes contextuales relacionados con los temas de esta ficha. Pide ejemplos de programas, apps, cobertura en Colombia y origen de la clasificación; no envíes estas frases como si fueran segmentos existentes.',test:'Contrasta dos paquetes contextuales con el mismo spot. Solicita frecuencia y alcance deduplicado, especificando si reportan hogares, dispositivos o personas.',metric:'Tasa de video completado, costo por reproducción completa y alcance en la unidad acordada.'}
 };
 if(!methods[medium])throw new Error('Medio inválido');
 return {...a,searches,topics,...methods[medium],productMessage:cleaning?'Demostrar limpieza y desmaquillado con algodón; mostrar el uso real del producto.':'Explicar el paso de tratamiento después de limpiar, la doble textura y la diferencia frente al algodón; respetar las indicaciones del empaque.',remarketing:medium==='ctv'?'Solo evaluar retargeting si el proveedor documenta identidad, consentimiento, cobertura y deduplicación. No asumir conexión con las audiencias sociales.':'Si existen datos propios autorizados y audiencias elegibles: proponer visitantes de la ficha del producto en 30 días e interacción con contenido en 30 días, en pruebas separadas. Excluir compradores recientes solo si existe el evento y la opción. Las ventanas son hipótesis, sujetas a disponibilidad y tamaño mínimo.',validation:'Validar distribución geográfica, inventario de categorías, etiquetado de eventos y piezas aprobadas. No inferir una condición médica ni asumir que consumir este contenido demuestra pertenencia al perfil.'};
}
